# Generated by Django 4.2 on 2025-01-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(null=True, upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('R', 'Rock'), ('F', 'Fire'), ('E', 'Electric'), ('G', 'Grass'), ('W', 'Water')], max_length=30),
        ),
    ]
