# Generated by Django 4.2 on 2024-12-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('W', 'Water'), ('E', 'Electric'), ('F', 'Fire'), ('R', 'Rock'), ('G', 'Grass')], max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
