# Generated by Django 4.2 on 2025-01-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type_alter_trainer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='level',
            field=models.IntegerField(),
        ),
    ]
